Controllers/CountryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using elearning_net.Models; 

namespace elearning_net.Controllers
{
    public class CountryController : Controller
    {

        String api_name = "country"; 

        // GET: Country  
        public ActionResult Index()
        {
            CountryModelAPI CountryModelAPI = new CountryModelAPI();
            ViewBag.listCountrys = CountryModelAPI.getAll(api_name); 

            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Add");
        }
        [HttpPost]
        public ActionResult Add(CountryModelSearch cvm)
        {
            CountryModelAPI CountryModelAPI = new CountryModelAPI();
            CountryModelAPI.post(api_name, cvm.country);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Detail(String id)
        {
            CountryModelAPI CountryModelAPI = new CountryModelAPI();
            CountryModelSearch CVM = new CountryModelSearch();
            CVM.country = CountryModelAPI.get(api_name, id);
            return View("Detail", CVM);
        }

        [HttpGet]
        public ActionResult Edit(String id)
        {
            CountryModelAPI CountryModelAPI = new CountryModelAPI();
            CountryModelSearch CVM = new CountryModelSearch();
            CVM.country = CountryModelAPI.get(api_name,id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(CountryModelSearch CVM)
        {
            CountryModelAPI CountryModelAPI = new CountryModelAPI();
            CountryModelAPI.put(api_name, CVM.country);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            CountryModelAPI CountryModelAPI = new CountryModelAPI();
            CountryModelAPI.delete(api_name, id);
            return RedirectToAction("Index");
        }
    }

}

Views/Country/Add.cshtml
@{ViewBag.Title = "Country Add";}
@model elearning_net.Models.CountryModelSearch

    <h2> Add </h2>

<div align = "center">
@using (Html.BeginForm("add", "Country", FormMethod.Post))
{ 
    <table class = "table"> 
    <tr>
        <td>@Html.LabelFor(model => model.country.country_name) </td>
        <td>@Html.TextBoxFor(model => model.country.country_name) </td> 
    </tr> 
    <tr>
        <td>@Html.LabelFor(model => model.country.phone_code) </td>
        <td>@Html.TextBoxFor(model => model.country.phone_code) </td> 
    </tr> 
    <tr>
        <td>@Html.LabelFor(model => model.country.country_code) </td>
        <td>@Html.TextBoxFor(model => model.country.country_code) </td> 
    </tr>  
    <tr>
        <td></td>
        <td><input class="btn btn-success" type = "submit" value = "Save"/></td> 
    </tr> 
</table>
} 
</div>  

Views/Country/Detail.cshtml
@{ViewBag.Title = "Country Detail";}
@model elearning_net.Models.CountryModelSearch

    <h2> Detail </h2>

<div align = "center">  
    <table class = "table">
    <tr>
        <td>@Html.LabelFor(model => model.country.country_name) </td>
        <td>@Html.DisplayFor(model => model.country.country_name) </td>
    </tr> 
    <tr>
        <td>@Html.LabelFor(model => model.country.phone_code) </td>
        <td>@Html.DisplayFor(model => model.country.phone_code) </td> 
    </tr> 
    <tr>
        <td>@Html.LabelFor(model => model.country.country_code) </td>
        <td>@Html.DisplayFor(model => model.country.country_code) </td> 
    </tr>  
</table> 
</div>  

Views/Country/Edit.cshtml
@{ViewBag.Title = "Country Edit";}
@model elearning_net.Models.CountryModelSearch

    <h2> Edit </h2>

<div align = "center">
@using (Html.BeginForm("edit", "Country", FormMethod.Post))
{ 
    <table class = "table">  
    <tr>
        <td>@Html.LabelFor(model => model.country.country_name) </td>
        <td>@Html.TextBoxFor(model => model.country.country_name) </td> 
    </tr> 
    <tr>
        <td>@Html.LabelFor(model => model.country.phone_code) </td>
        <td>@Html.TextBoxFor(model => model.country.phone_code) </td> 
    </tr> 
    <tr>
        <td>@Html.LabelFor(model => model.country.country_code) </td>
        <td>@Html.TextBoxFor(model => model.country.country_code) </td> 
    </tr>  
    <tr>
        <td></td>
        <td>
            <input class="btn btn-success" type = "submit" value = "Save"/> &nbsp; 
            <a class = "btn btn-danger" href = "@Url.Action("Index","Country")"> Back </a>
            @Html.HiddenFor(model => model.country.id) 
       </td>
    </tr> 
</table>
} 
</div>  

Views/Country/Index.cshtml
@{ViewBag.Title = "Country List";}

<h2> List </h2>

<div align = "center">
    <a class="btn btn-success" href = "@Url.Action("Add","Country")"> Add New Country </a> 
    <br/><br/>
    <table cellpadding = "2" class = "table" cellspacing = "2" border = "1">
    <tr class = "btn-primary">
        <th> id</th> 
        <th> country_name</th> 
        <th> phone_code</th> 
        <th> country_code</th>  
        <th> Action</th> 
    </tr>
    @foreach(var item in ViewBag.listCountrys)
    { 
        <tr>
            <td>@item.id</td> 
            <td>@item.country_name</td> 
            <td>@item.phone_code</td> 
            <td>@item.country_code</td>  
            <td> 
                <a class="btn btn-info" href="@Url.Action("Detail","Country",new {id= item.id})">Detail</a>   
                <a class="btn btn-warning" href="@Url.Action("Edit","Country",new {id= item.id})">Edit</a>   
                <a class="btn btn-danger" onclick="return confirm('Do you want to Delete?')" href="@Url.Action("Delete","Country",new {id= item.id})">Delete</a> 
            </td>
        </tr>
    } 
</table> 
</div>  