Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using elearning_net.Models; 

namespace elearning_net.Controllers
{
    public class CourseController : Controller
    {

        String api_name = "course"; 

        // GET: Course  
        public ActionResult Index()
        {
            CourseModelAPI CourseModelAPI = new CourseModelAPI();
            ViewBag.listCourses = CourseModelAPI.getAll(api_name); 

            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Add");
        }
        [HttpPost]
        public ActionResult Add(CourseModelSearch cvm)
        {
            CourseModelAPI CourseModelAPI = new CourseModelAPI();
            CourseModelAPI.post(api_name, cvm.course);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Detail(String id)
        {
            CourseModelAPI CourseModelAPI = new CourseModelAPI();
            CourseModelSearch CVM = new CourseModelSearch();
            CVM.course = CourseModelAPI.get(api_name, id);
            return View("Detail", CVM);
        }

        [HttpGet]
        public ActionResult Edit(String id)
        {
            CourseModelAPI CourseModelAPI = new CourseModelAPI();
            CourseModelSearch CVM = new CourseModelSearch();
            CVM.course = CourseModelAPI.get(api_name,id);
            return View("Edit", CVM);
        }
        [HttpPost]
        public ActionResult Edit(CourseModelSearch CVM)
        {
            CourseModelAPI CourseModelAPI = new CourseModelAPI();
            CourseModelAPI.put(api_name, CVM.course);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(String id)
        {
            CourseModelAPI CourseModelAPI = new CourseModelAPI();
            CourseModelAPI.delete(api_name, id);
            return RedirectToAction("Index");
        }
    }

}

Views/Course/Add.cshtml
@{ViewBag.Title = "Course Add";}
@model elearning_net.Models.CourseModelSearch

    <h2> Add </h2>

<div align = "center">
@using (Html.BeginForm("add", "Course", FormMethod.Post))
{ 
    <table class = "table"> 
    <tr>
        <td>@Html.LabelFor(model => model.course.course_name) </td>
        <td>@Html.TextBoxFor(model => model.course.course_name) </td> 
    </tr>  
    <tr>
        <td></td>
        <td><input class="btn btn-success" type = "submit" value = "Save"/></td> 
    </tr> 
</table>
} 
</div>  

Views/Course/Detail.cshtml
@{ViewBag.Title = "Course Detail";}
@model elearning_net.Models.CourseModelSearch

    <h2> Detail </h2>

<div align = "center">  
    <table class = "table">
    <tr>
        <td>@Html.LabelFor(model => model.course.course_name) </td>
        <td>@Html.DisplayFor(model => model.course.course_name) </td>
    </tr>  
</table> 
</div>  

Views/Course/Edit.cshtml
@{ViewBag.Title = "Course Edit";}
@model elearning_net.Models.CourseModelSearch

    <h2> Edit </h2>

<div align = "center">
@using (Html.BeginForm("edit", "Course", FormMethod.Post))
{ 
    <table class = "table">  
    <tr>
        <td>@Html.LabelFor(model => model.course.course_name) </td>
        <td>@Html.TextBoxFor(model => model.course.course_name) </td> 
    </tr>  
    <tr>
        <td></td>
        <td>
            <input class="btn btn-success" type = "submit" value = "Save"/> &nbsp; 
            <a class = "btn btn-danger" href = "@Url.Action("Index","Course")"> Back </a>
            @Html.HiddenFor(model => model.course.id) 
       </td>
    </tr> 
</table>
} 
</div>  

Views/Course/Index.cshtml
@{ViewBag.Title = "Course List";}

<h2> List </h2>

<div align = "center">
    <a class="btn btn-success" href = "@Url.Action("Add","Course")"> Add New Course </a> 
    <br/><br/>
    <table cellpadding = "2" class = "table" cellspacing = "2" border = "1">
    <tr class = "btn-primary">
        <th> id</th> 
        <th> course_name</th>  
        <th> Action</th> 
    </tr>
    @foreach(var item in ViewBag.listCourses)
    { 
        <tr>
            <td>@item.id</td> 
            <td>@item.course_name</td>  
            <td> 
                <a class="btn btn-info" href="@Url.Action("Detail","Course",new {id= item.id})">Detail</a>   
                <a class="btn btn-warning" href="@Url.Action("Edit","Course",new {id= item.id})">Edit</a>   
                <a class="btn btn-danger" onclick="return confirm('Do you want to Delete?')" href="@Url.Action("Delete","Course",new {id= item.id})">Delete</a> 
            </td>
        </tr>
    } 
</table> 
</div>  